name: Sandbox

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**.rego"

permissions:
  contents: read

jobs:
  opa:
    name: "Open Policy Agent Tests"
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: OPA setup
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      id: test
      run: |
        opa test opa/*.rego -v

    - name: OPA Test summary
      run: |
        echo -e '🎯 OPA test:' >> $GITHUB_STEP_SUMMARY
        echo -e '```none' >> $GITHUB_STEP_SUMMARY
        echo -e '${{ steps.test.outputs.stdout }}' >> $GITHUB_STEP_SUMMARY
        echo -e '```' >> $GITHUB_STEP_SUMMARY
