name: Sandbox

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**.rego"

permissions:
  contents: read

jobs:
  opa:
    name: "Open Policy Agent Tests"
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: OPA setup
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA tests
      id: test
      run: opa test opa/*.rego --verbose

    - name: OPA summary
      run: |
       {
         echo -e '🎯 OPA test:'
         echo -e '```opa'
         echo -e '${{ steps.test.outputs.stdout }}'
         echo -e '```'
       } >> "$GITHUB_STEP_SUMMARY"
